### ISSUE TITLE
inline compilation - source maps created only for main file

### ISSUE THREAD

**Issue by felixpis** [origin1tech/gulp-traceur-compiler#3]
I'm using gulp-traceur-compiler with option inline for modules.

gulp.task('compile/es6', function(){
    return gulp.src(['public/app/app.js'])
        .pipe(plugins.sourcemaps.init())
        .pipe(plugins.traceurCompiler({ modules: 'inline' }, true))
        .pipe(plugins.concat('compiled.js'))
        .pipe(plugins.sourcemaps.write('.'))
        .pipe(gulp.dest('dist'));
})

So output file contains all the application files imported in app.js. But source maps created only for app.js file. If I put in src "public/**/*.js", every module created several times in output file.
How can I create sourcemaps for all files in my case?
Thanks in advance

**Comment by tniswong** [comment]
+1

**Comment by origin1tech** [comment]
Sorry guys this has been deprecated. Please see the readme I made very detailed notes as to the why. We've tried every conceivable workflow and believe the workflow described at the top of the readme is your best option. Feel free to comment given time glad to explain further. Again apologies.
